version: '3'

services:
  bot:
    image: meiyounaise:latest
    build: ./
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: meiyounaise
    volumes:
      - ./database:/var/lib/postgresql/data
